"""Add new tables

Revision ID: 1258c0f2fb8e
Revises: 
Create Date: 2025-07-18 23:05:46.236890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import uuid


# revision identifiers, used by Alembic.
revision: str = '1258c0f2fb8e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Enum('BREAKFAST', 'LUNCH', 'DINNER', 'SUPPER', 'DESSERT', 'SNACK', name='categoryenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=True)

    category_table = sa.table(
        "category",
        sa.column("id", sa.Uuid),
        sa.column(
            "name",
            sa.Enum(
                "BREAKFAST",
                "LUNCH",
                "DINNER",
                "SUPPER",
                "DESSERT",
                "SNACK",
                name="categoryenum",
            ),
        ),
    )

    categories = [
        {"id": uuid.uuid4(), "name": "BREAKFAST"},
        {"id": uuid.uuid4(), "name": "LUNCH"},
        {"id": uuid.uuid4(), "name": "DINNER"},
        {"id": uuid.uuid4(), "name": "SUPPER"},
        {"id": uuid.uuid4(), "name": "DESSERT"},
        {"id": uuid.uuid4(), "name": "SNACK"},
    ]

    op.bulk_insert(category_table, categories)

    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredient',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recipe_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredient')
    op.drop_table('recipe')
    op.drop_table('user')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_table('category')
    op.execute("DROP TYPE categoryenum;")
    # ### end Alembic commands ###
