"""Fixed issue with different time in date_created and last_updated fields

Revision ID: 53c89b3bcef1
Revises: 8a6207fb3c13
Create Date: 2025-11-22 20:05:23.012576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53c89b3bcef1'
down_revision: Union[str, Sequence[str], None] = '8a6207fb3c13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
