"""Added cascade delete

Revision ID: 8a6207fb3c13
Revises: 8f341e134660
Create Date: 2025-11-18 21:35:27.097725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a6207fb3c13'
down_revision: Union[str, Sequence[str], None] = '8f341e134660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipe', 'date_added',
               existing_type=postgresql.TIMESTAMP())
    op.alter_column('user', 'date_created',
               existing_type=postgresql.TIMESTAMP())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'date_created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('recipe', 'date_added',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
