"""Added new fields in models: Recipe and User

Revision ID: 8f341e134660
Revises: 1258c0f2fb8e
Create Date: 2025-11-18 21:07:25.686612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f341e134660'
down_revision: Union[str, Sequence[str], None] = '1258c0f2fb8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('date_added', sa.DateTime()))
    op.add_column('recipe', sa.Column('last_updated', sa.DateTime()))
    op.add_column('user', sa.Column('date_created', sa.DateTime()))
    op.add_column('user', sa.Column('last_updated', sa.DateTime()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_updated')
    op.drop_column('user', 'date_created')
    op.drop_column('recipe', 'last_updated')
    op.drop_column('recipe', 'date_added')
    # ### end Alembic commands ###
